## TEST DATASET INITIALISATION

In [1]:
import sys
sys.path.append('../')

import numpy as np
import random
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data_utils

import datasets

In [2]:
m = 12
d = 8


In [3]:

train_size = 1000000 # size of the training set
test_size = 20000 # size of the test set

dataset = datasets.LinearModelxy(
        train_size = train_size,
        num_samples = m,
        dimension = d,
        seed_function=1,
        seed_sample=1,
        test_size=test_size,
        transform=None
)

In [4]:
x = dataset.samples
print(x.size())
print(x.mean(dim=1).mean())
print(x.norm(dim=1).mean())

torch.Size([1020000, 13, 9])
tensor(-6.1851e-05)
tensor(1.4851)


In [6]:
print(dir(dataset)) 

# for the input points call trainset.input
print(dataset.samples.size()) # dimension: train_size x num_features x input_size

# for the labels call trainset.output
print(dataset.labels.size()) # dimension: train_size

['__add__', '__class__', '__class_getitem__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__orig_bases__', '__parameters__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_is_protocol', 'dimension', 'labels', 'num_samples', 'samples', 'transform']
torch.Size([1020000, 13, 9])
torch.Size([1020000])


In [7]:
print(dataset.samples[0,:,:])

tensor([[-0.4864, -0.2392, -0.2085, -0.5131, -0.0319, -0.1942, -0.3124, -0.5130,
          3.1367],
        [-0.3382,  0.1442, -0.3692, -0.1194, -0.1056,  0.8013,  0.1085,  0.2221,
         -0.0998],
        [-0.3376, -0.5622,  0.3388,  0.0964,  0.4193,  0.1184, -0.3211,  0.3910,
          0.1313],
        [ 0.3590, -0.0573, -0.7317, -0.4713,  0.0199, -0.2013, -0.2600, -0.0429,
          1.1768],
        [ 0.8907, -0.0342,  0.0748, -0.3666,  0.0943,  0.0217,  0.0725, -0.2255,
         -0.5230],
        [-0.0358,  0.0943, -0.0509, -0.0093,  0.7595, -0.3342,  0.5074, -0.2029,
         -0.0111],
        [-0.3375,  0.1984,  0.0241, -0.1591,  0.2776,  0.1607,  0.4241,  0.7336,
         -1.1152],
        [ 0.0342,  0.2337, -0.0463, -0.1605,  0.3832, -0.2165, -0.8294, -0.1862,
          1.2668],
        [-0.0111, -0.4462, -0.2600, -0.4385, -0.0918, -0.0033,  0.7297,  0.0045,
          0.5165],
        [-0.3583, -0.0943, -0.5070, -0.4230, -0.2346, -0.2850,  0.2013, -0.4999,
          2.4341],


In [16]:
import math

lastfeat = torch.clone(dataset.features[:,:,-1])
print(lastfeat.size())

cls = torch.ones(v)/math.sqrt(v)
print(cls, cls.norm())
cls = torch.tile( cls, [train_size+test_size, 1])
print(cls.size())

dataset.features[:,:,-1] = cls
print(lastfeat[:10,:])

torch.Size([1020000, 10])
tensor([0.3162, 0.3162, 0.3162, 0.3162, 0.3162, 0.3162, 0.3162, 0.3162, 0.3162,
        0.3162]) tensor(1.)
torch.Size([1020000, 10])
tensor([[-0.1054, -0.1054, -0.1054, -0.1054, -0.1054,  0.9487, -0.1054, -0.1054,
         -0.1054, -0.1054],
        [ 0.9487, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054,
         -0.1054, -0.1054],
        [-0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054,
          0.9487, -0.1054],
        [-0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054,  0.9487,
         -0.1054, -0.1054],
        [-0.1054, -0.1054, -0.1054, -0.1054, -0.1054,  0.9487, -0.1054, -0.1054,
         -0.1054, -0.1054],
        [-0.1054,  0.9487, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054,
         -0.1054, -0.1054],
        [-0.1054,  0.9487, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054, -0.1054,
         -0.1054, -0.1054],
        [-0.1054, -0.1054, -0.1054, -0.1054, -0.1054,  0.9487, -0.1054, -0.10